---
title: "Intro to Gspam"
author: "Thayer Fisher"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## gspam

gspam is a collection of solvers aimed at solving the following problem:

$$\min_f\sum_{i=1}^{n}\ell(y_i,\sum_{j=1}^{p}f_j(x_{i,j})+\lambda_1\sum_{j=1}^{p}P(f_j)+\lambda_2\sum_{j=1}^{p}\Vert f_j\Vert_n$$

We do so by proximal gradient descent. Currently, the package supports logistic and quadratic losses, and fused lasso, polynomial basis, and categorical variational penalties.


## Examples
```{r eval = F}
# Predicting a binary outcome y from 1 categorical variable and 100 numerical variables.
  set.seed(1408)
  # Fused Lasso prox, log loss
  
  ## Set Params
  
  # Number of obs
  n <- 100
  # Number of features
  p <- 100
  # Number of numeric signal features
  s <- 5
  # Ratio of shape tuning parameter to sparsity tuning parameter
  alpha <- 0.5
  # Sample randomly from 3 categories
  cats <- c("yes", "no","maybe")
  cat_data <- sample(cats, n, replace =T)
  
  # Convert categories to numeric values labeled 0:(number_of_categories-1) so we can put them in a matrix and the solver can read them
  cats <-rownames(table(cat_data))
  numdata<-match(cat_data,cats)-1
  
  # X is random normal
  X <- matrix(rnorm(n*p),ncol=p)
  beta <- c(rep(1,s),rep(0,p-s))
  sig <- sign(X)
  Using logit link, generate y with signal (X*beta+(cat==no)-2*(cat==yes))
  y <- rbinom(n,size=1,prob=expit(sig %*% beta+(numdata== 1)-2*(numdata == 2)))
  # Vector for which the i'th entry specifies the prox function to be used for the i'th column of the data
  prox_type <- c("cat",rep("fl",p))
  # Run solver with log loss
  results <- gspam_full(cbind(numdata,X),y,prox_type,"log",0.5)


```

