# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Default Generalized Sparse Additive Model Solver with single
#' Prespecified variational penalty and lambda's
#' @description Fit model as specified by user for a single variational penalty
#' (matrix of X-values).
#' @name gspam_c
#' @param data n by p matrix of inputs
#' @param y response column vector
#' @param type of prox to use
#' @param sparsity penalty
#' @param variational penalty
gspam_c <- function(data, y, prox_type, loss_type, lambda1 = 0.0, lambda2 = 0.0) {
    .Call('_gspam_gspam_c', PACKAGE = 'gspam', data, y, prox_type, loss_type, lambda1, lambda2)
}

#' @title Default Generalized Sparse Additive Model Solver with vector of
#' prespecified variational penalties and sparsity penalties
#' @description Fit model as specified by user for a single variational penalty
#' (matrix of X-values).
#' @name gspam_c_vec
#' @param data n by p matrix of inputs
#' @param y response column vector
#' @param type of prox to use
#' @param sparsity penalties
#' @param variational penalties
gspam_c_vec <- function(data, y, prox_type, loss_type, lambda1, lambda2) {
    .Call('_gspam_gspam_c_vec', PACKAGE = 'gspam', data, y, prox_type, loss_type, lambda1, lambda2)
}

#' @title Default Generalized Sparse Additive Model Solver that calculates
#' lambda path based on mixture value.
#' @description Fit model as specified by user for calculated range of lambda
#' values.
#' @name gspam_full
#' @param data n by p matrix of inputs
#' @param y response column vector
#' @param type of prox to use
#' @param scalar value lambda2=alpha*lambda1
gspam_full <- function(data, y, prox_type, loss_type, alpha) {
    .Call('_gspam_gspam_full', PACKAGE = 'gspam', data, y, prox_type, loss_type, alpha)
}

#' @title Lambda path retrieval for given data and outcome
#' @name get_lambdas
#' @param data n by p matrix of inputs
#' @param y response column vector
#' @param type of prox to use
#' @param scalar value lambda2=alpha*lambda1
get_lambdas <- function(data, y, prox_type, loss_type, alpha) {
    .Call('_gspam_get_lambdas', PACKAGE = 'gspam', data, y, prox_type, loss_type, alpha)
}

#' @title Generalized Loss function
#' @description Applies specified loss to two vectors
#' @name gspam_c
#' @param y target of loss
#' @param theta fitted values
#' @param type type of loss to use
#' @export
loss <- function(y, theta, type) {
    .Call('_gspam_loss', PACKAGE = 'gspam', y, theta, type)
}

#' @title Generalized Loss Grad Function
#' @description Applies specified grad of loss to two vectors
#' @name gspam_c
#' @param y target of loss
#' @param theta fitted values
#' @param type type of loss to use
#' @export
grad <- function(y, theta, type) {
    .Call('_gspam_grad', PACKAGE = 'gspam', y, theta, type)
}

